on: push
name: Deploy on push
permissions:
  contents: write
jobs:
  prod-deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Get latest code
      uses: actions/checkout@master
      
    - name: Git pull
      run: git pull

    - name: Cleanup backup folder
      run: rm -rf ./release/prod/backup/*

    - name: Update backup folder
      run: cp -r ./release/prod/deploy/* ./release/prod/backup/

    - name: Cleanup deploy folder
      run: rm -rf ./release/prod/deploy/*

    - name: Build project
      run: |
        npm install
        npm run build-prod:ssr
    
    - name: Prepare deploy directory -> browser
      run: cp -r ./dist/nc-web-frontend/browser/* ./release/prod/deploy/

    - name: Prepare deploy directory -> server
      run: cp -r ./dist/nc-web-frontend/server ./release/prod/deploy/

    - name: Commit release file changes
      run: |
        git config --global user.name '${{ secrets.GIT_NAME }}'
        git config --global user.email '${{ secrets.GIT_EMAIL }}'
        git add .
        git commit -m "Github Action: Preparing release to production"
        git push

    - name: Sync files to FTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.NEW_CRE_FTP_PASSWORD }}
        local-dir: ./release/prod/deploy/
        server-dir: public_html/
        dry-run: true

  dev-deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'
    steps:
    - name: Get latest code
      uses: actions/checkout@master
      
    - name: Git pull
      run: git pull

    - name: Cleanup backup folder
      run: rm -rf ./release/staging/backup/*

    - name: Update backup folder
      run: cp -r ./release/staging/deploy/* ./release/staging/backup/

    - name: Cleanup deploy folder
      run: rm -rf ./release/staging/deploy/*

    - name: Build project
      run: |
        npm install
        npm run build-staging:ssr
    
    - name: Prepare deploy directory -> browser
      run: cp -r ./dist/nc-web-frontend/browser/* ./release/staging/deploy/

    - name: Prepare deploy directory -> server
      run: cp -r ./dist/nc-web-frontend/server ./release/staging/deploy/

    - name: Commit release file changes
      run: |
        git config --global user.name '${{ secrets.GIT_NAME }}'
        git config --global user.email '${{ secrets.GIT_EMAIL }}'
        git add .
        git commit -m "Github Action: Preparing release to development"
        git push

    - name: Sync files to FTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.NEW_CRE_FTP_PASSWORD }}
        local-dir: ./release/staging/deploy/
        server-dir: public_html/development/
        dry-run: false